### ISSUE TITLE
Check that SonarQube Core Badges is localized and localize Qualsign Badges

### ISSUE THREAD

**Issue by ghost** [1c-syntax/sonar-l10n-ru#8]
There is a badges plugin

https://github.com/QualInsight/qualinsight-plugins-sonarqube-badges

first off all we need to fix https://github.com/QualInsight/qualinsight-plugins-sonarqube-badges/issues/44
may be we need an pull request to official docker-alpine image

next - we need a localized badges ;-)

dirty hack - we need and string raplace in svg https://raw.githubusercontent.com/QualInsight/qualinsight-plugins-sonarqube-badges/master/images/measure_flat_ok.svg

```
sed -i -e 's/technical debt ratio on new code/технический долг в новом коде/g' measure_flat_ok.svg
```

And then rebuild plugin with `ru` suffix ;-)

**Comment by pawlakm** [comment]
Hi, if you need localisation just create an issue explaining what would be required on the plugin's side.

**Comment by allustin** [comment]
in 7.1/7.2 there is an new badges in core sonarqube - https://github.com/SonarSource/sonarqube/tree/master/server/sonar-server/src/main/java/org/sonar/server/badge/ws

Docs of this is localized https://github.com/SonarSource/sonarqube/blob/master/sonar-core/src/main/resources/org/sonar/l10n/core.properties#L2369

**Comment by theshadowco** [comment]
RIP
